version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: wealth_postgres
    environment:
      POSTGRES_USER: wealth_user
      POSTGRES_PASSWORD: wealth_password
      POSTGRES_DB: wealth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wealth_network

volumes:
  postgres_data:
    driver: local

networks:
  wealth_network:
    driver: bridge
