spring:
  logging:
    level:
      root: DEBUG
      org.springframework.security: DEBUG
  datasource:
    url: jdbc:postgresql://localhost:5432/wealth_db
    username: wealth_user
    password: wealth_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  mail:
    host: email-ssl.com.br
    port: 465
    username: noreply@prospero.com.br
    password:  Prospero@2025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
  expiration: 3600000  # 1 hour in milliseconds